version: "3"

services:
  web:
    build: .
    expose:
      - 80

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
