version: "3"

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - PORT=80
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
