name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  # deploy:
  #   name: Deploy to EC2 on master branch push
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout the files
  #       uses: actions/checkout@v2

  #     - name: Deploy to AWS EC2
  #       uses: easingthemes/ssh-deploy@main
  #       env:
  #         SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
  #         REMOTE_HOST: ${{ secrets.HOST_DNS }}
  #         REMOTE_USER: ${{ secrets.USERNAME }}
  #         TARGET: ${{ secrets.TARGET_DIR }}

  #     - name: Executing remote ssh commands using ssh key
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.HOST_DNS }}
  #         username: ${{ secrets.USERNAME }}
  #         key: ${{ secrets.EC2_SSH_KEY }}
  #         script: |
  #           cd home
  #           docker-compose dowm
  #           docker stop home-web-1
  #           docker-compose up -d

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_EMAIL }}
          password: ${{ secrets.DOCKERHUB_PW }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/app:latest
